### ISSUE TITLE
the title of the M-W Word of the Day toot

### ISSUE THREAD

**Issue by stipsmong** [AkiGoat/MWwordoftheday-bot#1]
the title of the M-W Word of the Day  became "Word of the day: Word of the Day", don't know if you could fix this, thx
![Screenshot 2023-02-22 160601](https://user-images.githubusercontent.com/30384476/220559920-b7e958b2-a49a-4e88-a703-ffca2092ec2d.jpg)

**Comment by AkiGoat** [comment]
Thank you for pointing it out! Now fixed. :D
